import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jet = JetBrains_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Animate Card Button",
  description: "Generated by Fernando Hiroshi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jet.className}>{children}</body>
    </html>
  );
}
